export const calendar: string;
export const day: string;
export const dayWeek: string;
export const isTasks: string;
export const selected: string;
export const spacer: string;
export const title: string;
export const wrapDays: string;
export const wrapDaysWeek: string;
